### ISSUE TITLE
Mysterious duplicates

### ISSUE THREAD

**Issue by iFA88** [sprymix/csscompressor#16]
Hey!
csscompressor 0.9.5 does the following issue:
From this:
```css
.form-floating > .form-control,
.form-floating > .form-control-plaintext,
.form-floating > .form-select {
  height: calc(3.5rem + calc(var(--bs-border-width) * 2));
  min-height: calc(3.5rem + calc(var(--bs-border-width) * 2));
  line-height: 1.25;
}
```
Does this:
```css
.form-floating>.form-control,.form-floating>.form-control-plaintext,.form-floating>.form-select{height:calc(3.5rem + calc(var(--bs-border-width) * 2))calc(var(--bs-border-width) * 2));min-height:calc(3.5rem + calc(var(--bs-border-width) * 2))calc(var(--bs-border-width) * 2));line-height:1.25}
```
